### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/juli#10]

**Comment by JesusFromHellz** [comment]
Any chances of getting back this idea?

**Comment by quanglam2807** [comment]
I'll try to work on this when I have time.

**Comment by JesusFromHellz** [comment]
Guessing you will work on this when you have time, and being this engine better than the actual browsers it supports, should I still report other engine's issues or rather let you work on it when you can?

**Comment by quanglam2807** [comment]
@JesusFromHellz Sure. Feel free to create issues for other engines in webcatalog/webcatalog
