### ISSUE TITLE
Add CLI support

### ISSUE THREAD

**Issue by seaneking** [webcatalog/juli#18]
Now that Juli is an app framework, how would I go about using it without WebCatalog? CLI options or something? Any plans to add docs for that? 

Would be awesome to generate apps myself with Juli as a shared runtime, rather than needing the webcatalog GUI/manager tacked on as well. FWIW I think that's the real value of what you've created - Juli as a kickass replacement for Nativefier, rather than a glorified backend for webcatalog.

**Comment by quanglam2807** [comment]
You can use this script: https://github.com/quanglam2807/webcatalog/blob/master/public/libs/install-app-async/appify-darwin.sh

**Comment by seaneking** [comment]
Awesome thanks. 

Would be great to automatically add Juli's CLI from that script to the user's /usr/local/bin and document it. Because that basically puts Juli standalone on par with Nativefier and co (if I understand correctly the apps I create with Juli still share a runtime, to 'update' them I just update Juli yeah?). No need for Juli to be solely an engine for WebCatalog when it can be easily used on its own like this too 👍

**Comment by quanglam2807** [comment]
Is there a reason why you prefer CLI?

**Comment by seaneking** [comment]
Not so much CLI vs GUI, it's having this whole separate management app when it's unecessary, especially now that you don't need update the bundles. If Juli had a simple app creator form when you open it directly (rather than a warning screen), like the 'custom app' form in webcatolog, that'd be just as good. The app bundles are already kept separate in `~/Applications/Juli Apps/`, no need for them to have their own separate management interface as well.

**Comment by quanglam2807** [comment]
The reason why I don't do that is to have a single code base. But I'll consider doing this if there're enough users.

**Comment by seaneking** [comment]
FWI created a little CLI tool to generate apps directly with Juli - https://github.com/seaneking/juli-cli 

Feel free to mention it in your docs or whatever, might be handy for other users.

**Comment by quanglam2807** [comment]
@seaneking Awesome! I'll add reference to the app soon :)

**Comment by seaneking** [comment]
Also if you want to merge it in to Juli itself go for it, not fussed :-)

**Comment by quanglam2807** [comment]
@seaneking What about a GitHub organization to keep all WebCatalog-related projects?

**Comment by quanglam2807** [comment]
@seaneking That was what I did before. But there's a problem: when user open an app with Juli as the engine, you won't be able to open Juli from the Launchpad. It can be fixed, but it's quirky. https://github.com/quanglam2807/appifier
