### ISSUE TITLE
Add option to customize titlebar color

### ISSUE THREAD

**Issue by Yukaii** [webcatalog/juli#48]
Tried adding custom titlebar via injected CSS/JS on `mobile.twitter.com` (twitter PWA) but not works as expected.

JS:

```js
var titlebar = document.createElement('div')
titlebar.className = 'juli-draggable-titlebar'
titlebar.style.position = 'fixed'
titlebar.style.height = '18px';
titlebar.style.width = '100%';
titlebar.style.top = 0;
titlebar.style.zIndex = 999999

document.body.appendChild(titlebar);
```

CSS:

```css
.juli-draggable-titlebar {
  -webkit-app-region: drag;
}
```

And there is an upstream issue https://github.com/electron/electron/issues/6791.

Is there any chance to implement custom titlebar as an option in Juli? Thank you.

**Comment by quanglam2807** [comment]
@Yukaii What OS are you using? Title bar option is already available on macOS.

**Comment by Yukaii** [comment]
I see that option, but can we customize the color of the title bar? I want it to look more immersive.
