### ISSUE TITLE
Using Juli outside Webcatalog, to package webapp?

### ISSUE THREAD

**Issue by mr-islam** [webcatalog/juli#49]
Hi, 

I was wondering: is it possible to package a webapp and use Juli engine instead of the Chromium like electron? 

WebCatalog can use Juli, but I want to directly package and make Windows/Mac/Linux package releases for my own webapp, because Juli is so lightweight and performant

Thanks :+1:

**Comment by quanglam2807** [comment]
@mr-islam Actually, Juli itself uses Electron under the hood so if it doesn't offer anything superior.
